services:
  # Search UI SPA
  - type: web
    name: osobisty-search-ui
    env: static
    autoDeploy: false
    repo: https://github.com/janaka/osobisty-search.git # optional, defaults to the repo this render.yaml is in.
    buildCommand: yarn --cwd ./search-ui && yarn --cwd ./search-ui build
    staticPublishPath: ./search-ui/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_AUTH0_AUDIENCE
        sync: false
      - key: REACT_APP_AUTH0_CLIENT_ID
        sync: false 
      - key: REACT_APP_AUTH0_DOMAIN
        sync: false
      - key: REACT_APP_TYPESENSE_HOST
        sync: false
      - key: REACT_APP_TYPESENSE_PORT
        fromService:
          name: osobisty-api
          type: web
          property: port
  # API
  - type: web
    name: osobisty-api
    env: node
    region: frankfurt
    autoDeploy: false
    repo: https://github.com/janaka/osobisty-search.git # optional, defaults to the repo this render.yaml is in.
    healthCheckPath: /ping
    buildCommand: yarn --cwd ./api && yarn --cwd ./api upgrade && yarn --cwd ./api build 
    startCommand: node ./api/build/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        sync: false
      - key: PORT
        value: 443
      - key: CORS_ORIGINS
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: TYPESENSE_HOST
        fromService:
          name: typesense-searchengine
          type: pserv
          property: host
      - key: TYPESENSE_PORT
        fromService:
          name: typesense-searchengine
          type: pserv
          property: port
      - key: TYPESENSE_API_KEY_ADMIN
        fromService:
          name: typesense-searchengine
          type: pserv
          envVarKey: TYPESENSE_API_KEY
      - key: TYPESENSE_API_KEY_READ_ZETTLEDOCS
        sync: false # placeholder for a value to be added in the dashboard
  # private Typesense Instance
  - type: pserv
    name: typesense-searchengine
    env: docker
    region: frankfurt
    autoDeploy: false
    repo: https://github.com/janaka/osobisty-search.git # optional, defaults to the repo this render.yaml is in.
    dockerfilePath: ./infra/typesense/Dockerfile
    dockerContext: ./infra/typesense
    envVars:
      - key: TYPESENSE_API_KEY
        sync: false # placeholder for a value to be added in the dashboard
    disk:
      name: data
      mountPath: /var/lib/typesense/data
      sizeGB: 1 # optional